import json
import sqlite3
import os
import re
from datetime import datetime, timezone

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # SQLite-only test and local environments
    psycopg = None
    dict_row = None

INTEGRITY_ERRORS = ((sqlite3.IntegrityError, psycopg.IntegrityError)
                    if psycopg else (sqlite3.IntegrityError,))


SCHEMA = """
CREATE TABLE IF NOT EXISTS opportunities (
 id INTEGER PRIMARY KEY AUTOINCREMENT, external_id TEXT UNIQUE, title TEXT,
 url TEXT, repository TEXT, reward REAL, license TEXT, status TEXT,
 risk_score INTEGER, expected_value REAL, reason TEXT, discovered_at TEXT
);
CREATE TABLE IF NOT EXISTS outcomes (
 id INTEGER PRIMARY KEY AUTOINCREMENT, opportunity_id INTEGER, result TEXT,
 income REAL DEFAULT 0, cost REAL DEFAULT 0, hours REAL DEFAULT 0,
 recorded_at TEXT, notes TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (
 id INTEGER PRIMARY KEY AUTOINCREMENT, event TEXT, details TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS learning_proposals (
 id INTEGER PRIMARY KEY AUTOINCREMENT, proposal TEXT, status TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS agent_records (
 id INTEGER PRIMARY KEY AUTOINCREMENT, external_id TEXT, agent TEXT,
 payload TEXT, created_at TEXT, UNIQUE(external_id, agent)
);
CREATE TABLE IF NOT EXISTS experience_cases (
 id INTEGER PRIMARY KEY AUTOINCREMENT, external_id TEXT UNIQUE, sampled_year INTEGER,
 repository TEXT, category TEXT, cycle_days INTEGER, comments INTEGER,
 labels TEXT, state_reason TEXT, source_url TEXT, learned_at TEXT
);
CREATE TABLE IF NOT EXISTS work_reviews (
 id INTEGER PRIMARY KEY AUTOINCREMENT, opportunity_id INTEGER, evidence_id TEXT UNIQUE,
 decision TEXT, payload TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS work_queue (
 id INTEGER PRIMARY KEY AUTOINCREMENT, opportunity_id INTEGER UNIQUE,
 stage TEXT, deliberation TEXT, created_at TEXT, updated_at TEXT
);
CREATE TABLE IF NOT EXISTS client_requests (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, email TEXT, project TEXT,
 budget TEXT, status TEXT, quote_cents INTEGER, quote_description TEXT,
 stripe_session_id TEXT UNIQUE, payment_status TEXT, created_at TEXT, updated_at TEXT
);
CREATE TABLE IF NOT EXISTS crm_syncs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, client_request_id INTEGER UNIQUE,
 provider TEXT, external_contact_id TEXT, synced_at TEXT
);
CREATE TABLE IF NOT EXISTS client_jobs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, client_request_id INTEGER UNIQUE,
 status TEXT, language TEXT, profile TEXT, acceptance_criteria TEXT,
 source_files TEXT, required_skills TEXT, changed_files TEXT, output_files TEXT,
 evidence TEXT, summary TEXT, model_response_id TEXT, error TEXT,
 created_at TEXT, updated_at TEXT
);
CREATE TABLE IF NOT EXISTS authority_decisions (
 id INTEGER PRIMARY KEY AUTOINCREMENT, client_job_id INTEGER, action TEXT,
 decision_id TEXT UNIQUE, status TEXT, actor TEXT, evidence TEXT, created_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_client_jobs_status ON client_jobs(status, id);
CREATE TABLE IF NOT EXISTS practice_runs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, exercise_id TEXT, category TEXT,
 difficulty INTEGER, score INTEGER, verified_pass INTEGER, evidence_id TEXT UNIQUE,
 lesson TEXT, result TEXT, created_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_practice_exercise_created
 ON practice_runs(exercise_id, created_at);
CREATE TABLE IF NOT EXISTS teacher_cycles (
 id INTEGER PRIMARY KEY AUTOINCREMENT, cycle_id TEXT UNIQUE, status TEXT,
 curriculum TEXT, accreditation TEXT, created_at TEXT
);
"""

POSTGRES_SCHEMA = """
CREATE SCHEMA IF NOT EXISTS bounty_builder;
SET search_path TO bounty_builder, public;
CREATE TABLE IF NOT EXISTS opportunities (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT UNIQUE, title TEXT,
 url TEXT, repository TEXT, reward DOUBLE PRECISION, license TEXT, status TEXT,
 risk_score INTEGER, expected_value DOUBLE PRECISION, reason TEXT, discovered_at TEXT
);
CREATE TABLE IF NOT EXISTS outcomes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT, result TEXT,
 income DOUBLE PRECISION DEFAULT 0, cost DOUBLE PRECISION DEFAULT 0, hours DOUBLE PRECISION DEFAULT 0,
 recorded_at TEXT, notes TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event TEXT, details TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS learning_proposals (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, proposal TEXT, status TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS agent_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT, agent TEXT, payload TEXT, created_at TEXT, UNIQUE(external_id, agent));
CREATE TABLE IF NOT EXISTS experience_cases (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT UNIQUE, sampled_year INTEGER, repository TEXT, category TEXT, cycle_days INTEGER, comments INTEGER, labels TEXT, state_reason TEXT, source_url TEXT, learned_at TEXT);
CREATE TABLE IF NOT EXISTS work_reviews (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT, evidence_id TEXT UNIQUE, decision TEXT, payload TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS work_queue (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT UNIQUE, stage TEXT, deliberation TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS client_requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, email TEXT, project TEXT, budget TEXT, status TEXT, quote_cents INTEGER, quote_description TEXT, stripe_session_id TEXT UNIQUE, payment_status TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS crm_syncs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_request_id BIGINT UNIQUE, provider TEXT, external_contact_id TEXT, synced_at TEXT);
CREATE TABLE IF NOT EXISTS client_jobs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_request_id BIGINT UNIQUE, status TEXT, language TEXT, profile TEXT, acceptance_criteria TEXT, source_files TEXT, required_skills TEXT, changed_files TEXT, output_files TEXT, evidence TEXT, summary TEXT, model_response_id TEXT, error TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS authority_decisions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_job_id BIGINT, action TEXT, decision_id TEXT UNIQUE, status TEXT, actor TEXT, evidence TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS practice_runs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exercise_id TEXT, category TEXT, difficulty INTEGER, score INTEGER, verified_pass INTEGER, evidence_id TEXT UNIQUE, lesson TEXT, result TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS teacher_cycles (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cycle_id TEXT UNIQUE, status TEXT, curriculum TEXT, accreditation TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS migration_state (name TEXT PRIMARY KEY, completed_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_client_jobs_status ON client_jobs(status, id);
CREATE INDEX IF NOT EXISTS idx_practice_exercise_created ON practice_runs(exercise_id, created_at);
REVOKE ALL ON SCHEMA bounty_builder FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA bounty_builder FROM PUBLIC, anon, authenticated;
"""


class PostgresConnection:
    def __init__(self, url):
        self.raw = psycopg.connect(url, row_factory=dict_row,
                                   options="-c search_path=bounty_builder,public")

    def __enter__(self): return self
    def __exit__(self, kind, value, traceback):
        self.raw.rollback() if kind else self.raw.commit()
        self.raw.close()

    def executescript(self, script):
        self.raw.execute(script)

    def execute(self, query, params=()):
        if query.strip().upper().startswith("PRAGMA"):
            return EmptyCursor()
        sql = query.replace("BEGIN IMMEDIATE", "BEGIN")
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, flags=re.I)
        sql = re.sub(r"VALUES\s*\(NULL,", "VALUES(DEFAULT,", sql, flags=re.I)
        sql = sql.replace("SUM(status='ACCREDITED')", "COUNT(*) FILTER (WHERE status='ACCREDITED')")
        sql = sql.replace("SUM(status='APPROVED')", "COUNT(*) FILTER (WHERE status='APPROVED')")
        sql = sql.replace("SUM(status='REJECTED')", "COUNT(*) FILTER (WHERE status='REJECTED')")
        replace_review = bool(re.search(r"INSERT\s+OR\s+REPLACE\s+INTO\s+work_reviews", query, re.I))
        if replace_review:
            sql = re.sub(r"INSERT\s+OR\s+REPLACE\s+INTO", "INSERT INTO", sql, flags=re.I)
            sql += " ON CONFLICT(evidence_id) DO UPDATE SET decision=excluded.decision, payload=excluded.payload, created_at=excluded.created_at"
        elif re.search(r"INSERT\s+OR\s+IGNORE", query, re.I) and "ON CONFLICT" not in sql.upper():
            sql += " ON CONFLICT DO NOTHING"
        sql = sql.replace("?", "%s")
        wants_id = bool(re.match(r"\s*INSERT INTO (outcomes|client_requests|client_jobs)\b", sql, re.I))
        if wants_id and "RETURNING" not in sql.upper():
            sql += " RETURNING id"
        cursor = self.raw.execute(sql, params) if params else self.raw.execute(sql)
        return PgCursor(cursor, wants_id)


class PgCursor:
    def __init__(self, cursor, capture_id=False):
        self.cursor = cursor
        self.rowcount = cursor.rowcount
        self.lastrowid = None
        if capture_id:
            row = cursor.fetchone()
            self.lastrowid = row["id"] if row else None
    def fetchone(self): return self.cursor.fetchone()
    def fetchall(self): return self.cursor.fetchall()
    def __iter__(self): return iter(self.cursor)


class EmptyCursor:
    rowcount = 0
    lastrowid = None
    def fetchone(self): return None
    def fetchall(self): return []
    def __iter__(self): return iter(())


class Store:
    def __init__(self, path: str):
        self.path = path
        self.postgres = path.startswith(("postgres://", "postgresql://"))
        if self.postgres and psycopg is None:
            raise RuntimeError("psycopg is required when DATABASE_URL is configured")
        with self.connect() as db:
            if self.postgres:
                ready = db.execute("SELECT COUNT(*) ready FROM migration_state").fetchone()
                if ready is None:
                    raise RuntimeError("PostgreSQL schema is not initialized")
            else:
                db.execute("PRAGMA journal_mode=WAL")
                db.executescript(SCHEMA)

    def connect(self):
        if self.postgres:
            return PostgresConnection(self.path)
        db = sqlite3.connect(self.path)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA busy_timeout=5000")
        return db

    def audit(self, event, details):
        with self.connect() as db:
            db.execute("INSERT INTO audit_log VALUES(NULL,?,?,?)",
                       (event, json.dumps(details), now()))

    def save_opportunity(self, item):
        with self.connect() as db:
            db.execute("""INSERT INTO opportunities VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?)
              ON CONFLICT(external_id) DO UPDATE SET title=excluded.title,
              url=excluded.url, repository=excluded.repository, reward=excluded.reward,
              license=excluded.license, status=excluded.status,
              risk_score=excluded.risk_score, expected_value=excluded.expected_value,
              reason=excluded.reason""", (
                item["external_id"], item["title"], item["url"], item["repository"],
                item["reward"], item["license"], item["status"], item["risk_score"],
                item["expected_value"], item["reason"], now()))
            for key, agent in (("repository_analysis", "repository_analyst"),
                               ("risk_compliance", "risk_compliance_agent"),
                               ("solution_plan", "solution_planner")):
                if item.get(key) is not None:
                    db.execute("""INSERT INTO agent_records VALUES(NULL,?,?,?,?)
                      ON CONFLICT(external_id,agent) DO UPDATE SET
                      payload=excluded.payload, created_at=excluded.created_at""",
                      (item["external_id"], agent, json.dumps(item[key]), now()))

    def save_practice_run(self, result):
        with self.connect() as db:
            cursor = db.execute("""INSERT OR IGNORE INTO practice_runs
              VALUES(NULL,?,?,?,?,?,?,?,?,?)""", (
                result["exercise_id"], result["category"], result["difficulty"],
                result["score"], int(result["verified_pass"]), result["evidence_id"],
                result["lesson"], json.dumps(result), now(),
            ))
        return cursor.rowcount

    def practice_stats(self):
        with self.connect() as db:
            row = db.execute("""SELECT COUNT(*) drills,
              COALESCE(SUM(verified_pass),0) verified_passes,
              COALESCE(ROUND(AVG(score),1),0) average_score,
              COALESCE(MAX(difficulty),0) max_difficulty FROM practice_runs""").fetchone()
            return dict(row)

    def practice_history(self):
        """Return bounded metadata only; source and test code are never stored."""
        with self.connect() as db:
            rows = db.execute("SELECT result FROM practice_runs ORDER BY id").fetchall()
        return [json.loads(row["result"]) for row in rows]

    def save_teacher_cycle(self, cycle):
        accreditation = cycle["accreditation"]
        with self.connect() as db:
            cursor = db.execute("""INSERT OR IGNORE INTO teacher_cycles
              VALUES(NULL,?,?,?,?,?)""", (cycle["cycle_id"], accreditation["status"],
              json.dumps(cycle["curriculum"]), json.dumps(accreditation), now()))
        return cursor.rowcount

    def latest_teacher_cycle(self):
        with self.connect() as db:
            row = db.execute("SELECT * FROM teacher_cycles ORDER BY id DESC LIMIT 1").fetchone()
        if not row:
            return None
        item = dict(row)
        item["curriculum"] = json.loads(item["curriculum"])
        item["accreditation"] = json.loads(item["accreditation"])
        return item

    def teacher_stats(self):
        with self.connect() as db:
            row = db.execute("""SELECT COUNT(*) cycles,
              COALESCE(SUM(status='ACCREDITED'),0) accredited_cycles
              FROM teacher_cycles""").fetchone()
        return dict(row)

    def skill_profile(self):
        """Summarize only sandbox-verified practice evidence."""
        languages = {}
        verified_skills = set()
        scores = []
        max_difficulty = 0
        with self.connect() as db:
            rows = db.execute("""SELECT category, difficulty, score, result
              FROM practice_runs WHERE verified_pass=1""").fetchall()
        language_scores = {}
        skill_scores = {}
        for row in rows:
            payload = json.loads(row["result"])
            language = str(payload.get("language") or "unknown")
            language_scores.setdefault(language, []).append(row["score"])
            verified_skills.add(row["category"])
            scores.append(row["score"])
            max_difficulty = max(max_difficulty, row["difficulty"])
            skill = skill_scores.setdefault(row["category"], {"scores": [], "max_difficulty": 0})
            skill["scores"].append(row["score"])
            skill["max_difficulty"] = max(skill["max_difficulty"], row["difficulty"])
        for language, values in language_scores.items():
            languages[language] = {
                "verified_passes": len(values),
                "average_score": round(sum(values) / len(values), 1),
            }
        skills = {name: {"verified_passes": len(value["scores"]),
                         "average_score": round(sum(value["scores"]) / len(value["scores"]), 1),
                         "max_difficulty": value["max_difficulty"]}
                  for name, value in skill_scores.items()}
        return {"verified_skills": sorted(verified_skills), "skills": skills,
                "languages": languages,
                "verified_passes": len(scores),
                "average_score": round(sum(scores) / len(scores), 1) if scores else 0,
                "max_difficulty": max_difficulty}

    def reject_unseen_approvals(self, seen_external_ids):
        """Remove stale approvals after a complete scan without deleting history."""
        seen = {str(value) for value in seen_external_ids}
        with self.connect() as db:
            rows = db.execute(
                "SELECT external_id FROM opportunities WHERE status='APPROVED'"
            ).fetchall()
            stale = [row["external_id"] for row in rows if row["external_id"] not in seen]
            if stale:
                placeholders = ",".join("?" for _ in stale)
                db.execute(
                    f"""UPDATE opportunities SET status='REJECTED', risk_score=0,
                    reason='REJECT_NOT_IN_LATEST_COMPLETE_SCAN'
                    WHERE external_id IN ({placeholders})""",
                    stale,
                )
        return len(stale)

    def list_opportunities(self, limit=100):
        with self.connect() as db:
            return [dict(row) for row in db.execute(
                "SELECT * FROM opportunities ORDER BY risk_score DESC, id DESC LIMIT ?", (limit,))]

    def get_opportunity(self, opportunity_id):
        with self.connect() as db:
            row = db.execute("SELECT * FROM opportunities WHERE id=?", (opportunity_id,)).fetchone()
            return dict(row) if row else None

    def agent_records_for(self, external_id):
        with self.connect() as db:
            rows = db.execute("""SELECT agent, payload, created_at FROM agent_records
              WHERE external_id=? ORDER BY agent""", (external_id,))
            return [{**dict(row), "payload": json.loads(row["payload"])} for row in rows]

    def agent_record_map(self, external_id):
        return {row["agent"].replace("repository_analyst", "repository_analysis")
                .replace("risk_compliance_agent", "risk_compliance")
                .replace("solution_planner", "solution_plan"): row["payload"]
                for row in self.agent_records_for(external_id)}

    def recent_audit(self, limit=100):
        with self.connect() as db:
            rows = db.execute("SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,))
            return [{**dict(row), "details": json.loads(row["details"])} for row in rows]

    def record_outcome(self, opportunity_id, result, income, cost, hours, notes):
        with self.connect() as db:
            exists = db.execute("SELECT 1 FROM opportunities WHERE id=?", (opportunity_id,)).fetchone()
            if not exists:
                raise KeyError("opportunity not found")
            cursor = db.execute("INSERT INTO outcomes VALUES(NULL,?,?,?,?,?,?,?)",
                (opportunity_id, result, income, cost, hours, now(), notes))
            outcome_id = cursor.lastrowid
        self.audit("outcome_recorded", {"outcome_id": outcome_id,
                   "opportunity_id": opportunity_id, "result": result,
                   "income": income, "cost": cost, "hours": hours})
        return outcome_id

    def outcomes(self):
        with self.connect() as db:
            return [dict(row) for row in db.execute("SELECT * FROM outcomes ORDER BY id")]

    def performance_rows(self):
        with self.connect() as db:
            return [dict(row) for row in db.execute("""SELECT o.*, p.url, p.repository,
              'unknown' language FROM outcomes o LEFT JOIN opportunities p
              ON p.id=o.opportunity_id ORDER BY o.id""")]

    def save_learning_proposal(self, proposal):
        with self.connect() as db:
            db.execute("INSERT INTO learning_proposals VALUES(NULL,?,?,?)",
                       (json.dumps(proposal), proposal.get("status", "proposal_only"), now()))

    def save_experience(self, cases):
        saved = 0
        with self.connect() as db:
            for case in cases:
                cursor = db.execute("""INSERT OR IGNORE INTO experience_cases
                  VALUES(NULL,?,?,?,?,?,?,?,?,?,?)""", (case["external_id"],
                  case["sampled_year"], case["repository"], case["category"],
                  case["cycle_days"], case["comments"], json.dumps(case["labels"]),
                  case["state_reason"], case["source_url"], now()))
                saved += cursor.rowcount
        return saved

    def experience_stats(self):
        with self.connect() as db:
            row = db.execute("""SELECT COUNT(*) cases, COUNT(DISTINCT sampled_year) years,
              ROUND(AVG(cycle_days),1) average_cycle_days FROM experience_cases""").fetchone()
            categories = {r["category"]: r["count"] for r in db.execute(
                "SELECT category, COUNT(*) count FROM experience_cases GROUP BY category")}
            return {**dict(row), "categories": categories}

    def save_work_review(self, opportunity_id, decision, payload):
        with self.connect() as db:
            if not db.execute("SELECT 1 FROM opportunities WHERE id=?", (opportunity_id,)).fetchone():
                raise KeyError("opportunity not found")
            db.execute("INSERT OR REPLACE INTO work_reviews VALUES(NULL,?,?,?,?,?)",
                (opportunity_id, decision["evidence_id"], decision["status"],
                 json.dumps(payload), now()))
        self.audit("delivery_reviewed", {"opportunity_id": opportunity_id, **decision})

    def enqueue_work(self, opportunity_id, deliberation):
        stage = ({"AUTO_APPROVE_ISOLATED_BUILD": "READY_FOR_ISOLATED_BUILD",
                  "QUEUE_FOR_DANIEL_APPROVAL": "AWAITING_DANIEL_APPROVAL"}
                 .get(deliberation["recommendation"], "TRAINING_REQUIRED"))
        with self.connect() as db:
            db.execute("""INSERT INTO work_queue VALUES(NULL,?,?,?,?,?)
              ON CONFLICT(opportunity_id) DO UPDATE SET stage=excluded.stage,
              deliberation=excluded.deliberation, updated_at=excluded.updated_at""",
              (opportunity_id, stage, json.dumps(deliberation), now(), now()))
        return stage

    def work_queue(self, limit=100):
        with self.connect() as db:
            rows = db.execute("""SELECT q.*, p.title, p.repository, p.reward,
              p.expected_value, p.url FROM work_queue q JOIN opportunities p
              ON p.id=q.opportunity_id ORDER BY p.expected_value DESC LIMIT ?""", (limit,))
            return [{**dict(row), "deliberation": json.loads(row["deliberation"])} for row in rows]

    def expire_stale_work(self):
        """Mark non-current queued bounty work stale without deleting history."""
        with self.connect() as db:
            cursor = db.execute("""UPDATE work_queue SET stage='STALE_NOT_CURRENT', updated_at=?
              WHERE opportunity_id IN (SELECT id FROM opportunities WHERE status!='APPROVED')
              AND stage IN ('AWAITING_DANIEL_APPROVAL','READY_FOR_ISOLATED_BUILD',
                            'TRAINING_REQUIRED','BLOCKED_MODEL_NOT_CONFIGURED')""", (now(),))
            return cursor.rowcount

    def claim_ready_bounty(self):
        """Claim one fresh internally authorized bounty for isolated building."""
        with self.connect() as db:
            row = db.execute("""SELECT q.*, p.external_id, p.title, p.repository,
              p.reward, p.expected_value, p.url FROM work_queue q
              JOIN opportunities p ON p.id=q.opportunity_id
              WHERE q.stage='READY_FOR_ISOLATED_BUILD' AND p.status='APPROVED'
              ORDER BY p.expected_value DESC, q.id ASC LIMIT 1""").fetchone()
            if not row:
                return None
            cursor = db.execute("""UPDATE work_queue SET stage='BUILDING', updated_at=?
              WHERE id=? AND stage='READY_FOR_ISOLATED_BUILD'""", (now(), row["id"]))
            if cursor.rowcount != 1:
                return None
            result = dict(row)
            result["stage"] = "BUILDING"
            result["deliberation"] = json.loads(result["deliberation"])
            return result

    def set_bounty_stage(self, queue_id, stage):
        allowed = {
            'READY_FOR_ISOLATED_BUILD', 'BUILDING', 'AWAITING_DANIEL_DELIVERY_REVIEW',
            'TESTS_FAILED', 'BUILD_FAILED', 'BLOCKED_MODEL_NOT_CONFIGURED',
            'STALE_NOT_CURRENT',
        }
        if stage not in allowed:
            raise ValueError("invalid bounty stage")
        with self.connect() as db:
            cursor = db.execute("UPDATE work_queue SET stage=?, updated_at=? WHERE id=?",
                                (stage, now(), queue_id))
            if cursor.rowcount != 1:
                raise KeyError("work queue item not found")
        return stage

    def agent_activity(self):
        with self.connect() as db:
            records = {row["agent"]: row["count"] for row in db.execute(
                "SELECT agent, COUNT(*) count FROM agent_records GROUP BY agent")}
            scans = db.execute("SELECT COUNT(*) count FROM audit_log WHERE event LIKE 'scout_%'").fetchone()["count"]
            proposals = db.execute("SELECT COUNT(*) count FROM learning_proposals").fetchone()["count"]
            return {
                "opportunity_scout": scans,
                "repository_analyst": records.get("repository_analyst", 0),
                "risk_compliance_agent": records.get("risk_compliance_agent", 0),
                "solution_planner": records.get("solution_planner", 0),
                "performance_learner": proposals,
                "historical_experience": self.experience_stats()["cases"],
                "delivery_reviews": db.execute("SELECT COUNT(*) count FROM work_reviews").fetchone()["count"],
                "deep_deliberations": db.execute("SELECT COUNT(*) count FROM work_queue").fetchone()["count"],
                "practice": self.practice_stats(),
                "teacher": self.teacher_stats(),
            }

    def stats(self):
        with self.connect() as db:
            row = db.execute("""SELECT COUNT(*) found,
              SUM(status='APPROVED') approved,
              SUM(status='REJECTED') rejected,
              COALESCE(SUM(CASE WHEN status='APPROVED' THEN expected_value ELSE 0 END),0)
              expected_value FROM opportunities""").fetchone()
            money = db.execute("SELECT COALESCE(SUM(income-cost),0) amount FROM outcomes").fetchone()["amount"]
            return {**dict(row), "realized_income": round(money, 2),
                    "agent_activity": self.agent_activity()}

    def create_client_request(self, name, email, project, budget):
        timestamp = now()
        with self.connect() as db:
            cursor = db.execute("""INSERT INTO client_requests
              (name,email,project,budget,status,payment_status,created_at,updated_at)
              VALUES(?,?,?,?,?,?,?,?)""",
              (name, email, project, budget, "NEW", "UNPAID", timestamp, timestamp))
            request_id = cursor.lastrowid
        self.audit("client_request_received", {"client_request_id": request_id})
        return request_id

    def get_client_request(self, request_id):
        with self.connect() as db:
            row = db.execute("SELECT * FROM client_requests WHERE id=?", (request_id,)).fetchone()
            return dict(row) if row else None

    def list_client_requests(self, limit=100):
        with self.connect() as db:
            return [dict(row) for row in db.execute(
                "SELECT * FROM client_requests ORDER BY id DESC LIMIT ?", (limit,))]

    def record_crm_sync(self, request_id, provider, external_contact_id):
        with self.connect() as db:
            db.execute("""INSERT INTO crm_syncs VALUES(NULL,?,?,?,?)
              ON CONFLICT(client_request_id) DO UPDATE SET provider=excluded.provider,
              external_contact_id=excluded.external_contact_id,
              synced_at=excluded.synced_at""",
              (request_id, provider, external_contact_id, now()))
        self.audit("client_synced_to_crm", {"client_request_id": request_id,
                   "provider": provider, "external_contact_id": external_contact_id})

    def get_crm_sync(self, request_id):
        with self.connect() as db:
            row = db.execute("SELECT * FROM crm_syncs WHERE client_request_id=?",
                             (request_id,)).fetchone()
            return dict(row) if row else None

    def quote_client_request(self, request_id, amount_cents, description):
        with self.connect() as db:
            cursor = db.execute("""UPDATE client_requests SET status='QUOTED',
              quote_cents=?, quote_description=?, updated_at=? WHERE id=?""",
              (amount_cents, description, now(), request_id))
            if not cursor.rowcount:
                raise KeyError("client request not found")
        self.audit("client_quote_approved", {"client_request_id": request_id,
                   "amount_cents": amount_cents})

    def set_checkout_session(self, request_id, session_id):
        with self.connect() as db:
            db.execute("""UPDATE client_requests SET stripe_session_id=?,
              status='CHECKOUT_READY', updated_at=? WHERE id=?""",
              (session_id, now(), request_id))

    def mark_client_request_paid(self, session_id, payment_status):
        with self.connect() as db:
            row = db.execute("SELECT id FROM client_requests WHERE stripe_session_id=?",
                             (session_id,)).fetchone()
            if not row:
                return None
            request_id = row["id"]
            db.execute("""UPDATE client_requests SET payment_status=?, status='PAID',
              updated_at=? WHERE id=?""", (payment_status, now(), request_id))
        self.audit("client_payment_confirmed", {"client_request_id": request_id,
                   "stripe_session_id": session_id})
        return request_id

    def create_client_job(self, request_id, language, profile, acceptance_criteria,
                          source_files, required_skills):
        timestamp = now()
        with self.connect() as db:
            request = db.execute("SELECT * FROM client_requests WHERE id=?", (request_id,)).fetchone()
            if not request:
                raise KeyError("client request not found")
            if request["status"] != "PAID" or request["payment_status"] != "paid":
                raise PermissionError("verified payment required")
            cursor = db.execute("""INSERT INTO client_jobs
              (client_request_id,status,language,profile,acceptance_criteria,source_files,
               required_skills,changed_files,output_files,evidence,summary,model_response_id,
               error,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
              (request_id, "QUEUED", language, profile, json.dumps(acceptance_criteria),
               json.dumps(source_files), json.dumps(required_skills), "[]", "{}", "{}",
               "", "", "", timestamp, timestamp))
            job_id = cursor.lastrowid
        self.audit("client_job_queued", {"client_job_id": job_id,
                   "client_request_id": request_id, "language": language,
                   "required_skills": required_skills})
        return job_id

    def claim_client_job(self):
        with self.connect() as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT id FROM client_jobs WHERE status='QUEUED' ORDER BY id LIMIT 1").fetchone()
            if not row:
                return None
            db.execute("UPDATE client_jobs SET status='BUILDING',updated_at=? WHERE id=?",
                       (now(), row["id"]))
            job = db.execute("""SELECT j.*,r.project FROM client_jobs j JOIN client_requests r
              ON r.id=j.client_request_id WHERE j.id=?""", (row["id"],)).fetchone()
        return self._decode_client_job(job)

    def finish_client_job(self, job_id, result):
        with self.connect() as db:
            db.execute("""UPDATE client_jobs SET status=?,changed_files=?,output_files=?,
              evidence=?,summary=?,model_response_id=?,error='',updated_at=? WHERE id=?""",
              (result.status, json.dumps(result.changed_files), json.dumps(result.output_files),
               json.dumps({**result.evidence, "source_digest": result.source_digest,
                           "output_digest": result.output_digest}), result.summary,
               result.model_response_id, now(), job_id))
        self.audit("client_job_built", {"client_job_id": job_id, "status": result.status,
                   "changed_files": result.changed_files, "evidence": result.evidence})

    def fail_client_job(self, job_id, error):
        with self.connect() as db:
            db.execute("UPDATE client_jobs SET status='BLOCKED',error=?,updated_at=? WHERE id=?",
                       (str(error)[:1000], now(), job_id))
        self.audit("client_job_blocked", {"client_job_id": job_id,
                   "error": type(error).__name__, "message": str(error)[:300]})

    def record_authority_decision(self, job_id, action, decision, actor="authority_engine"):
        with self.connect() as db:
            db.execute("""INSERT OR IGNORE INTO authority_decisions
              VALUES(NULL,?,?,?,?,?,?,?)""", (job_id, action, decision["decision_id"],
              decision["status"], actor, json.dumps(decision), now()))
        self.audit("authority_decided", {"client_job_id": job_id, "action": action,
                   "decision_id": decision["decision_id"], "status": decision["status"],
                   "actor": actor})

    def approve_client_delivery(self, job_id, note):
        with self.connect() as db:
            row = db.execute("SELECT status,evidence FROM client_jobs WHERE id=?", (job_id,)).fetchone()
            if not row:
                raise KeyError("client job not found")
            if row["status"] != "AWAITING_DELIVERY_REVIEW":
                raise PermissionError("job is not ready for delivery approval")
            db.execute("UPDATE client_jobs SET status='DANIEL_APPROVED_FOR_DELIVERY',updated_at=? WHERE id=?",
                       (now(), job_id))
        payload = {"job_id": job_id, "action": "final_delivery", "note": note[:500],
                   "evidence": json.loads(row["evidence"] or "{}")}
        decision = {"action": "final_delivery", "status": "DANIEL_APPROVED",
                    "authorized": True, "scope": "delivery_only",
                    "decision_id": sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()[:20]}
        self.record_authority_decision(job_id, "final_delivery", decision, actor="daniel")
        return decision

    def authority_decisions(self, limit=100):
        with self.connect() as db:
            rows = db.execute("SELECT * FROM authority_decisions ORDER BY id DESC LIMIT ?",
                              (limit,)).fetchall()
        return [{**dict(row), "evidence": json.loads(row["evidence"])} for row in rows]

    def get_client_job(self, job_id):
        with self.connect() as db:
            row = db.execute("""SELECT j.*,r.project FROM client_jobs j JOIN client_requests r
              ON r.id=j.client_request_id WHERE j.id=?""", (job_id,)).fetchone()
        return self._decode_client_job(row) if row else None

    def list_client_jobs(self, limit=100):
        with self.connect() as db:
            rows = db.execute("""SELECT j.*,r.project FROM client_jobs j JOIN client_requests r
              ON r.id=j.client_request_id ORDER BY j.id DESC LIMIT ?""", (limit,)).fetchall()
        return [self._decode_client_job(row, include_code=False) for row in rows]

    @staticmethod
    def _decode_client_job(row, include_code=True):
        item = dict(row)
        for key, empty in (("acceptance_criteria", []), ("required_skills", []),
                           ("changed_files", []), ("evidence", {})):
            item[key] = json.loads(item.get(key) or json.dumps(empty))
        if include_code:
            item["source_files"] = json.loads(item.get("source_files") or "{}")
            item["output_files"] = json.loads(item.get("output_files") or "{}")
        else:
            item.pop("source_files", None)
            item.pop("output_files", None)
        return item


def now():
    return datetime.now(timezone.utc).isoformat()
