CREATE SCHEMA IF NOT EXISTS bounty_builder;
SET search_path TO bounty_builder, public;

CREATE TABLE IF NOT EXISTS opportunities (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT UNIQUE, title TEXT, url TEXT, repository TEXT, reward DOUBLE PRECISION, license TEXT, status TEXT, risk_score INTEGER, expected_value DOUBLE PRECISION, reason TEXT, discovered_at TEXT);
CREATE TABLE IF NOT EXISTS outcomes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT, result TEXT, income DOUBLE PRECISION DEFAULT 0, cost DOUBLE PRECISION DEFAULT 0, hours DOUBLE PRECISION DEFAULT 0, recorded_at TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event TEXT, details TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS learning_proposals (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, proposal TEXT, status TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS agent_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT, agent TEXT, payload TEXT, created_at TEXT, UNIQUE(external_id, agent));
CREATE TABLE IF NOT EXISTS experience_cases (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT UNIQUE, sampled_year INTEGER, repository TEXT, category TEXT, cycle_days INTEGER, comments INTEGER, labels TEXT, state_reason TEXT, source_url TEXT, learned_at TEXT);
CREATE TABLE IF NOT EXISTS work_reviews (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT, evidence_id TEXT UNIQUE, decision TEXT, payload TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS work_queue (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, opportunity_id BIGINT UNIQUE, stage TEXT, deliberation TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS client_requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, email TEXT, project TEXT, budget TEXT, status TEXT, quote_cents INTEGER, quote_description TEXT, stripe_session_id TEXT UNIQUE, payment_status TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS crm_syncs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_request_id BIGINT UNIQUE, provider TEXT, external_contact_id TEXT, synced_at TEXT);
CREATE TABLE IF NOT EXISTS client_jobs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_request_id BIGINT UNIQUE, status TEXT, language TEXT, profile TEXT, acceptance_criteria TEXT, source_files TEXT, required_skills TEXT, changed_files TEXT, output_files TEXT, evidence TEXT, summary TEXT, model_response_id TEXT, error TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS authority_decisions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_job_id BIGINT, action TEXT, decision_id TEXT UNIQUE, status TEXT, actor TEXT, evidence TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS practice_runs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exercise_id TEXT, category TEXT, difficulty INTEGER, score INTEGER, verified_pass INTEGER, evidence_id TEXT UNIQUE, lesson TEXT, result TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS teacher_cycles (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cycle_id TEXT UNIQUE, status TEXT, curriculum TEXT, accreditation TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS migration_state (name TEXT PRIMARY KEY, completed_at TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS idx_client_jobs_status ON client_jobs(status, id);
CREATE INDEX IF NOT EXISTS idx_practice_exercise_created ON practice_runs(exercise_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_records_external ON agent_records(external_id, agent);

REVOKE ALL ON SCHEMA bounty_builder FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA bounty_builder FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA bounty_builder FROM PUBLIC, anon, authenticated;
